version: '2'
services:
  mongodb:
    image: 'bitnami/mongodb:3.7-ol-7'
    volumes:
      - 'mongodb_data:/bitnami'
  parse:
    image: 'bitnami/parse:2-ol-7'
    ports:
      - '1337:1337'
    volumes:
      - 'parse_data:/bitnami'
    depends_on:
      - mongodb
volumes:
  mongodb_data:
    driver: local
  parse_data:
    driver: local
